// GENERATED by scripts/sync-skill.ts from packages/console/public/_headers (rules "/*" and "/").
// Pages Functions responses skip _headers, so the function for `/` sets these itself.
export const ROOT_HEADERS: Record<string, string> = {};
