#!/usr/bin/env -S npx tsx
/**
 * sync-skill: the agent front door (WS1). Regenerates every surface derived
 * from skills/basedagents/SKILL.md and checks the skill against the API and
 * CLI it describes.
 *
 *   npx tsx scripts/sync-skill.ts           # write every derived surface
 *   npx tsx scripts/sync-skill.ts --check   # exit 1 on drift or a broken reference (CI)
 *
 * Derived surfaces:
 *   packages/web/public/skill.md                                  (canonical URL)
 *   packages/web/public/skills/basedagents/SKILL.md               (latest)
 *   packages/web/public/skills/basedagents/v<version>/SKILL.md    (pinned, immutable)
 *   packages/web/public/skills/basedagents/skill.json             (manifest with sha256)
 *   packages/console/public/skill.md                              (for negotiation on app.)
 *   packages/{web,console}/public/.well-known/basedagents.json     (service descriptor)
 *   packages/api/src/discovery/skill.generated.ts                 (the API serves both)
 *   packages/web/public/llms-full.txt                             (skill + API summary + Keyring guide)
 *   packages/{web,console}/functions/headers.generated.ts          (headers for `/` responses)
 *
 * Checks (both modes):
 *   - every `METHOD /path` in SKILL.md exists in the OpenAPI spec;
 *   - every `basedagents <command> [sub] --flag` exists in the CLI registry;
 *   - min_cli_version is not newer than the SDK package version;
 *   - a pinned copy never changes without a version bump.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildDescriptor } from '../packages/api/src/discovery/descriptor.js';
import { findCommand } from '../packages/sdk/src/cli/commands.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const SITE = 'https://basedagents.ai';
const drift: string[] = [];
const errors: string[] = [];

const read = (rel: string) => readFileSync(join(ROOT, rel), 'utf8');

function upsert(rel: string, next: string): void {
  const abs = join(ROOT, rel);
  const cur = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (cur === next) return;
  if (CHECK) { drift.push(rel); return; }
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, next);
  console.log(`synced ${rel}`);
}

// ── Source + front matter ──
const SRC = 'skills/basedagents/SKILL.md';
const skill = read(SRC);
const fm = /^---\n([\s\S]*?)\n---\n/.exec(skill);
if (!fm) throw new Error(`${SRC}: missing front matter`);
const meta: Record<string, string> = {};
for (const line of fm[1].split('\n')) {
  const m = /^([a-z_]+):\s*(.*)$/.exec(line);
  if (m) meta[m[1]] = m[2].trim();
}
const SEMVER = /^\d+\.\d+\.\d+$/;
const version = meta.version;
if (!SEMVER.test(version ?? '')) errors.push(`${SRC}: version "${version}" is not semver`);
if (!/^\d{4}-\d{2}-\d{2}$/.test(meta.updated ?? '')) errors.push(`${SRC}: updated "${meta.updated}" is not YYYY-MM-DD`);
if (!SEMVER.test(meta.min_cli_version ?? '')) errors.push(`${SRC}: min_cli_version "${meta.min_cli_version}" is not semver`);
const body = skill.slice(fm[0].length);
const sha256 = createHash('sha256').update(skill, 'utf8').digest('hex');

// ── 1. Served copies ──
upsert('packages/web/public/skill.md', skill);
upsert('packages/web/public/skills/basedagents/SKILL.md', skill);
upsert('packages/console/public/skill.md', skill);
{
  const pinned = `packages/web/public/skills/basedagents/v${version}/SKILL.md`;
  const abs = join(ROOT, pinned);
  if (existsSync(abs) && readFileSync(abs, 'utf8') !== skill) {
    errors.push(`${pinned} exists with different content: SKILL.md changed without a version bump. Bump "version" in ${SRC}.`);
  } else {
    upsert(pinned, skill);
  }
}

// ── 2. Manifest ──
const manifest = {
  name: meta.name ?? 'basedagents',
  version,
  url: `${SITE}/skill.md`,
  pinnedUrl: `${SITE}/skills/basedagents/v${version}/SKILL.md`,
  sha256,
  updatedAt: meta.updated,
  minCliVersion: meta.min_cli_version,
  changelogUrl: `${SITE}/changelog`,
};
upsert('packages/web/public/skills/basedagents/skill.json', JSON.stringify(manifest, null, 2) + '\n');

// ── 3. Descriptor (site + console static copies; the API builds the same object live) ──
const descriptor = JSON.stringify(buildDescriptor({ version }), null, 2) + '\n';
upsert('packages/web/public/.well-known/basedagents.json', descriptor);
upsert('packages/console/public/.well-known/basedagents.json', descriptor);

// ── 4. API module ──
upsert('packages/api/src/discovery/skill.generated.ts', `// GENERATED by scripts/sync-skill.ts from ${SRC}. Do not edit.
export const SKILL_VERSION = ${JSON.stringify(version)};
export const SKILL_SHA256 = ${JSON.stringify(sha256)};
export const SKILL_UPDATED = ${JSON.stringify(meta.updated)};
export const SKILL_MIN_CLI_VERSION = ${JSON.stringify(meta.min_cli_version)};
export const SKILL_MD = ${JSON.stringify(skill)};
`);

// ── 5. llms-full.txt: skill + API summary + the Keyring/sandbox guide ──
type Op = { summary?: string };
const openapi = JSON.parse(read('packages/api/src/openapi.json')) as { paths: Record<string, Record<string, Op>> };
const METHODS = ['get', 'post', 'put', 'patch', 'delete'];
const apiLines: string[] = [];
for (const path of Object.keys(openapi.paths).sort()) {
  for (const m of METHODS) {
    const op = openapi.paths[path][m];
    if (op) apiLines.push(`- ${m.toUpperCase()} ${path}${op.summary ? ` — ${op.summary}` : ''}`);
  }
}
upsert('packages/web/public/llms-full.txt', `# BasedAgents — full

> The task marketplace for AI agents. Every agent holds a permanent ag_ identity
> (Ed25519 + proof-of-work); buyers post tasks, agents claim and deliver signed
> receipts, and bounties are paid in USDC on Base.
>
> GENERATED from ${SITE}/skill.md (the agent runbook, v${version}) plus the API
> summary and the Keyring guide. Machine-readable: ${SITE}/.well-known/basedagents.json

${body.trim()}

## API summary

Base: https://api.basedagents.ai · OpenAPI: https://api.basedagents.ai/v1/openapi.json

${apiLines.join('\n')}

${read('skills/basedagents/partials/keyring-and-sandboxes.md').trim()}

## Links

- Skill (this runbook): ${SITE}/skill.md · manifest: ${SITE}/skills/basedagents/skill.json
- Service descriptor: ${SITE}/.well-known/basedagents.json
- Agent manifest: ${SITE}/.well-known/agent.json
- Agent docs: ${SITE}/docs/agents
- Keyring: ${SITE}/keyring
- Get started (human): https://app.basedagents.ai/start
- Source: https://github.com/maxfain/basedagents
`);

// ── 6. Headers for the negotiated `/` responses (Pages Functions skip _headers) ──
function headersFor(rel: string, paths: string[]): Record<string, string> {
  const abs = join(ROOT, rel);
  const out: Record<string, string> = {};
  if (!existsSync(abs)) return out;
  let current: string | null = null;
  for (const line of readFileSync(abs, 'utf8').split('\n')) {
    if (!line.trim() || line.trim().startsWith('#')) continue;
    if (!/^\s/.test(line)) { current = line.trim(); continue; }
    if (current && paths.includes(current)) {
      const i = line.indexOf(':');
      if (i > 0) out[line.slice(0, i).trim()] = line.slice(i + 1).trim();
    }
  }
  return out;
}
for (const pkg of ['web', 'console']) {
  const h = headersFor(`packages/${pkg}/public/_headers`, ['/*', '/']);
  upsert(`packages/${pkg}/functions/headers.generated.ts`, `// GENERATED by scripts/sync-skill.ts from packages/${pkg}/public/_headers (rules "/*" and "/").
// Pages Functions responses skip _headers, so the function for \`/\` sets these itself.
export const ROOT_HEADERS: Record<string, string> = ${JSON.stringify(h, null, 2)};
`);
}

// ── 7. Reference checks ──
const normPath = (p: string) => p.replace(/\?.*$/, '').replace(/[.,;:)]+$/, '').replace(/\{[^}]+\}/g, '{}');
const specOps = new Set<string>();
for (const [path, item] of Object.entries(openapi.paths)) {
  for (const m of METHODS) if (item[m]) specOps.add(`${m.toUpperCase()} ${normPath(path)}`);
}
for (const m of body.matchAll(/\b(GET|POST|PUT|PATCH|DELETE) (\/[A-Za-z0-9_\-/{}.?=&]+)/g)) {
  const op = `${m[1]} ${normPath(m[2])}`;
  if (!specOps.has(op)) errors.push(`${SRC}: "${m[1]} ${m[2]}" is not in packages/api/src/openapi.json`);
}
for (const span of body.matchAll(/`([^`]*\bbasedagents(?:@latest)? [^`]*)`/g)) {
  const cmd = /\bbasedagents(?:@latest)? ([a-z][a-z-]*)(?: ([a-z][a-z-]*))?/.exec(span[1]);
  if (!cmd) continue;
  const entry = findCommand(cmd[1], cmd[2]);
  if (!entry) { errors.push(`${SRC}: \`${span[1]}\` — no CLI command "${cmd[1]}${cmd[2] ? ` ${cmd[2]}` : ''}"`); continue; }
  for (const f of span[1].matchAll(/\s(--[a-z][a-z-]*)/g)) {
    if (!entry.flags.includes(f[1])) errors.push(`${SRC}: \`${span[1]}\` — "${entry.command}${entry.sub ? ` ${entry.sub}` : ''}" has no flag ${f[1]}`);
  }
}
{
  const sdkVersion = (JSON.parse(read('packages/sdk/package.json')) as { version: string }).version;
  const cmp = (a: string, b: string) => { const x = a.split('.').map(Number), y = b.split('.').map(Number); for (let i = 0; i < 3; i++) if (x[i] !== y[i]) return x[i] - y[i]; return 0; };
  if (SEMVER.test(meta.min_cli_version ?? '') && cmp(meta.min_cli_version, sdkVersion) > 0) {
    errors.push(`${SRC}: min_cli_version ${meta.min_cli_version} is newer than packages/sdk (${sdkVersion})`);
  }
}

if (errors.length || drift.length) {
  for (const e of errors) console.error(`✗ ${e}`);
  if (drift.length) console.error(`✗ out of date (run: npx tsx scripts/sync-skill.ts):\n  ${drift.join('\n  ')}`);
  process.exit(1);
}
console.log(CHECK ? `skill v${version}: surfaces in sync, references resolve (sha256 ${sha256.slice(0, 12)}…)` : `skill v${version} synced`);
